apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metacontroller
  namespace: config-scmvanilla-uf8u2e
spec:
  chart:
    spec:
      chart: ./metacontroller
      sourceRef:
        kind: GitRepository
        name: siebel-repo
        namespace: config-scmvanilla-uf8u2e
  install:
    timeout: 30m
  interval: 10m0s
  releaseName: config-scmvanilla-uf8u2e-metacontroller
  uninstall:
    timeout: 30m
  values:
    image:
      pullPolicy: IfNotPresent
      registry: phx.ocir.io
      repository: siebeldev/cm/metacontroller
      tag: v4.11.5
