apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx
  namespace: config-scmvanilla-z6w8eq
spec:
  chart:
    spec:
      chart: ./ingress-nginx
      sourceRef:
        kind: GitRepository
        name: siebel-repo
        namespace: config-scmvanilla-z6w8eq
  install:
    timeout: 30m
  interval: 10m0s
  releaseName: config-scmvanilla-z6w8eq-ingress-nginx
  targetNamespace: config-scmvanilla-z6w8eq
  uninstall:
    timeout: 30m
  values:
    controller:
      admissionWebhooks:
        enabled: false
      config:
        enable-underscores-in-headers: 'true'
      image:
        image: siebeldev/cm/ingress-nginx
        registry: phx.ocir.io
        tag: v1.12.1
      ingressClass: config-scmvanilla-z6w8eq-nginx
      ingressClassByName: true
      ingressClassResource:
        controllerValue: k8s.io/config-scmvanilla-z6w8eq-ingress-nginx
        default: false
        enabled: true
        name: config-scmvanilla-z6w8eq-nginx
      metrics:
        enabled: true
      podAnnotations:
        prometheus.io/port: '10254'
        prometheus.io/scrape: 'true'
      scope:
        enabled: true
        namespace: config-scmvanilla-z6w8eq
      service:
        annotations:
          oci.oraclecloud.com/load-balancer-type: lb
          service.beta.kubernetes.io/oci-load-balancer-internal: 'false'
          service.beta.kubernetes.io/oci-load-balancer-shape: flexible
          service.beta.kubernetes.io/oci-load-balancer-shape-flex-max: 100
          service.beta.kubernetes.io/oci-load-balancer-shape-flex-min: 10
          service.beta.kubernetes.io/oci-load-balancer-ssl-ports: '443'
          service.beta.kubernetes.io/oci-load-balancer-tls-secret: lb-tls-certificate
        targetPorts:
          http: http
          https: http
        type: LoadBalancer
    imagePullSecrets:
    - name: ocirsecret
