apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: siebel-repo
  namespace: config-scmvanilla-z6w8eq
spec:
  interval: 5m
  ref:
    branch: main
  url: ssh://git@/git@github.com:cheolminhwang/cheolminhwang/helm3.git
  secretRef:
    name: flux-system
    #Using the flux-system's in built secret. If using any other repo outside flux-system hosted repo (other server or other services like gitlab or github) we need use the custom secrte like the one below.