apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: scmvanilla
spec:
  interval: 10m0s
  dependsOn:
    - name: infrastructure
    - name: siebel-operator
  sourceRef:
    kind: GitRepository
    name: scmvanilla
    namespace: scmvanilla
  path: ./FluxFolder/apps/staging
  prune: true
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: siebel
      namespace: scmvanilla