apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: scmvanilla
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: scmvanilla
    namespace: scmvanilla
  path: ./FluxFolder/infrastructure
  prune: true
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: nginx
      namespace: scmvanilla