apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metacontroller
  namespace: scmvanilla
spec:
  interval: 10m0s
  dependsOn:
    - name: infrastructure
  sourceRef:
    kind: GitRepository
    name: scmvanilla
    namespace: scmvanilla
  path: ./FluxFolder/metacontroller
  prune: true
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: metacontroller
      namespace: scmvanilla