apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: siebel-operator
  namespace: scmvanilla
spec:
  interval: 10m0s
  dependsOn:
    - name: metacontroller
  sourceRef:
    kind: GitRepository
    name: siebel-repo
    namespace: scmvanilla
  path: ./siebel-operator
  targetNamespace: scmvanilla
  prune: true